---
title: "Monte Hall Problem"
output: html_notebook
---


```{r}
library(bnlearn)
library(gRain)
library(tidyverse)
library(gt)
```
# The simple model.
P = Prize door
D = Door choice
M = Door revealed by Monty
```{r}
sdag <- model2network("[P][D][M|P:D]")
graphviz.plot(sdag, layout = "dot")
```

```{r}
# set the levels 
levels_D <- c("door1", "door2", "door3")
levels_P <- c("door1", "door2", "door3")
levels_M <- c("door1", "door2", "door3")


# NPTs
D_prob <- array(rep(1/3, 3), dim = 3, dimnames = list(D = levels_D))
P_prob <- array(rep(1/3, 3), dim = 3, dimnames = list(P = levels_P))
M_prob <- array(
  c(0, 0.5, 0.5, 0, 0, 1, 0, 1, 0, 
    0, 0, 1, 0.5, 0 , 0.5, 1, 0, 0, 
    0, 1, 0, 1, 0, 0, 0.5, 0.5, 0),
  dim = c(3, 3, 3),
  dimnames = list(M = levels_M, D = levels_D, P = levels_P)
)

# CPT for the model
cpt <- list(D = D_prob, P = P_prob, M = M_prob)

fitted <- custom.fit(sdag, cpt)
arcs <- as.data.frame(arcs(fitted))
nparams(fitted)
```
```{r}
M_prob
```


```{r, fig.height=8, fig.width=10}
graphviz.chart(fitted, type = "barprob", strip.bg = "lightskyblue", 
                bar.col = "darkgreen", scale = c(2,3))
```   
```{r, fig.height=10, fig.width=10}
ev <- (D == "door1") & (M == "door2")

# draw samples
updated_dat <- cpdist(fitted, nodes = bnlearn::nodes(fitted), evidence = ev)
updated_fit <- bn.fit(sdag, data = updated_dat)

graphviz.chart(updated_fit)

```




```{r}
junction <- compile(as.grain(fitted))

# set evidence
evidence <- list(D = "door1", M = "door2")

j_inst <- setEvidence(junction, 
                     nodes = names(evidence), 
                     states = unlist(evidence))
fitted$P
querygrain(j_inst, nodes = "P")

```

```{r, fig.height=8, fig.width=8}
D_inst <- array(c(1, 0, 0), dim = 3, dimnames = list(D = levels_D))
M_inst <- array(c(0, 1, 0), dim = 3, dimnames = list(M = levels_M))

# CPT for the model
cpt2 <- list(D = D_inst, P = P_prob, M = M_inst)

fitted2 <- custom.fit(sdag, cpt2)

graphviz.chart(fitted2, type = "barprob", strip.bg = "lightskyblue", 
                bar.col = "darkgreen", scale = c(2,3))
```


# Complex Model

C = Initial door choice
P = Prize door
M = Door revealed by Monty
S = Switch or stick?
F = Door choice after reveal
R = Win prize?
```{r}
mdag <- model2network(
  "[C][P][S][M|C:P][F|M:C:S][R|P:F]"
)  
graphviz.plot(mdag, layout = "circo")

```
## Define level vectors
```{r}

levels_C <- c("door1", "door2", "door3")
levels_P <- c("door1", "door2", "door3")
levels_F <- c("door1", "door2", "door3")
levels_M <- c("door1", "door2", "door3")
levels_S <- c("switch", "stick")
levels_R <- c("win", "lose")

```

## Assign conditonal distribution probabilities
```{r}

C_prob <- array(rep(1/3, 3), dim = 3, dimnames = list(C = levels_C))
P_prob <- array(rep(1/3, 3), dim = 3, dimnames = list(P = levels_P))
S_prob <- array(c(1/2, 1/2), dim = 2, dimnames = list(S = levels_S))

M_prob <- array(
  c(0, 1/2, 1/2, 0, 0, 1, 0, 1, 0,
    0, 0, 1, 1/2, 0 , 1/2, 1, 0 , 0,
    0, 1, 0, 1, 0, 0, 1/2, 1/2, 0), 
  dim = c(3, 3, 3), 
  dimnames = list(M = levels_M, C = levels_C, P = levels_P)
)

F_prob <- array(
  c(1/3, 1/3, 1/3, 1/3, 1/3, 1/3, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0 , 0,
    0, 0, 1, 0, 1, 0, 1/3, 1/3, 1/3, 1/3, 1/3,  1/3, 1, 0, 0, 0, 1, 0,
    0, 1, 0, 0 , 0 ,1, 1, 0, 0, 0, 0, 1, 1/3, 1/3, 1/3, 1/3, 1/3, 1/3),
  dim = c(3, 2, 3, 3),
  dimnames = list(F = levels_F, S = levels_S, M = levels_M, C = levels_C)
)

R_prob <- array(
  c(0, 1, 1, 0, 1, 0,
    1, 0, 0, 1, 1, 0, 
    1, 0, 1, 0, 0, 1),
  dim = c(2, 3, 3),
  dimnames = list(R = levels_R, P = levels_P, F = levels_F)
)
```

```{r}
cpt <- list(P = P_prob, C = C_prob, M = M_prob,
            S = S_prob, F = F_prob, R = R_prob)

bn <- custom.fit(mdag, cpt)
print(nparams(bn))
print(arcs(bn))
```

```{r}
evidence <- list(C = "door1")
cpquery(bn, event = (F == "door1"), evidence = (C == "door1"))
```

```{r}
junction <- compile(as.grain(bn))

jdoor1<- setEvidence(
  junction, 
  nodes = "C",
  states = "door1"
)

jdoor1<- setEvidence(
  junction, 
  nodes = "M",
  states = "door2"
)

evidence <- list(C = "door1", M = "door2")

jtest <- setEvidence(junction, nodes = names(evidence), states = unlist(evidence))
# corresponds to P(T | S = F)
querygrain(jtest, nodes = "F")
querygrain(jtest, nodes = "M")
```

